#!/usr/bin/env bash

# Create a new note in the notes directory. Prefixed with the current date.
main() {
	[[ -z $1 ]] && error "Note name must not be empty"

	local name=${1// /-}
	name=$(echo "$name" | tr '[:upper:]' '[:lower:]')
	local base_path="$HOME/Documents/Wiki/notes"
	$EDITOR "$base_path/$(date +'%y-%m-%d')-$name.md"
}

error() {
	local message=$1
	local code=${2:-1}
	echo "$message"
	exit "$code"
}

main "$@"
