#!/usr/bin/env bash

# Tmux helper. 

# Inspired and adapted from here: https://github.com/junegunn/fzf/wiki/Examples#tmux
tmuxkillf () {
  local target_sessions current_session
  current_session=$(tmux display-message -p '#S')
  target_sessions=$(tmux ls | \
    cut -d: -f1 | \
    sed "/$current_session/d" | \
    fzf --exit-0 --query="$1" --multi --exit-0) || return $?

  for session in $target_sessions; do
    session=${session%%:*}
    tmux kill-session -t "$session"
  done
}

tmuxkillf "$@"
